openapi: 3.0.1
info:
  title: '@jupiterone/graph-kandji'
  description: A JupiterOne Integration for ingesting data of Kandji
  x-cortex-git:
    github:
      repository: JupiterOne/graph-kandji
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-kandji'
  x-cortex-service-groups:
    - tier-4
